owner: netbox-community
repo: netbox-chart
remote: origin
target-branch: develop
timeout: 10m
sign: true
key: builds@netboxlabs.com
keyring: ~/.cr-gpg/secring.gpg
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
generate-release-notes: true
