{{- if and .Values.reportsPersistence.enabled (not .Values.reportsPersistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-reports
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.reportsPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.reportsPersistence.size | quote }}
  {{- if .Values.reportsPersistence.storageClass }}
  {{- if (eq "-" .Values.reportsPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.reportsPersistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.reportsPersistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
