{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-media" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- if and .Values.reportsPersistence.enabled (not .Values.reportsPersistence.existingClaim) -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-reports" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.reportsPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.reportsPersistence.size | quote }}
  {{- if .Values.reportsPersistence.storageClass }}
  {{- if (eq "-" .Values.reportsPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.reportsPersistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.reportsPersistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- if and .Values.scriptsPersistence.enabled (not .Values.scriptsPersistence.existingClaim) -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-scripts" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.scriptsPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.scriptsPersistence.size | quote }}
  {{- if .Values.scriptsPersistence.storageClass }}
  {{- if (eq "-" .Values.scriptsPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.scriptsPersistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.scriptsPersistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
